### ISSUE TITLE
OTP is not working when using Microsoft Authenticator and Cisco Duo

### ISSUE THREAD

**Issue by draskomikic** [merixstudio/django-trench#154] opened 2022-04-20 12:50 UTC
**Describe the bug**
During the process of activating MFA method the code generated by Google and Lastpass apps is working while for Microsoft Authenticator and Cisco Duo is not working. 

The OTP QR code was generated in following format: 
`otpauth://totp/MyWebApp:myUser?secret=OTQGJNAJOUQP3UYIETRA2B4XOLJAYRFEP4W37PGYG37K5V35FEJCA7D66DCBZUSLRD3NR45J63CSNDLIJPJGWAT3OIORPGGJOBAIMFTZGCMA3F2U2JC2NJ7AGTXOPK6F77FJODQ6KK5PN2MV5XGWSJLYUMF2G74J&issuer=MyWebApp&period=60`

All authenticator apps (Google, Lastpass, Microsoft Authenticator and Cisco Duo) were successfully able to scan QR code, add account and generate OTP but it only worked for Google and Lastpass.

I am receiving following response on the `app/activate/confirm/` API endpoint for the Microsoft Authenticator and Cisco Duo:
`{"code":["Code invalid or expired."]}`

**To Reproduce**
1. Create MFA method in Django Trench for app (Authenticator app)
2. Generate and scan QR code or enter Account name and code manually using Microsoft Authenticator or Cisco Duo apps.
3. Try to activate MFA method using code generated by app.
4. Check the response

**Expected behavior**
To be able to activate MFA method using Microsoft Authenticator or Cisco Duo apps.

**Comment by jhurej** [comment] 2022-04-26 17:06
Hey @draskomikic, thanks for reporting.Could you specify in what version of django-trench you're facing this issue? It could be probably a duplicate of this issue https://github.com/merixstudio/django-trench/issues/136.  I'll try reproducign it for Microsoft Authenticator and Cisco Duo in django-trench version 0.3.1 in a meantime

**Comment by jhurej** [comment] 2022-04-27 13:54
I confirm that after scanning QR code with Microsoft Authenticator app, that codes generated by app doesn't match what's django-trench expects. I'm working on finding the root cause of this behavior.

**Comment by jhurej** [comment] 2022-04-27 20:37
@draskomikic I confirm the issue in django-trench 0.3.1 with Cisco Duo Mobile app one time codes. For some reason, it's possible to generate the one time code that django-trench accept but the time window when a given one time code is valid is less than 30 seconds, something like 10 seconds as far I can see. I'll seek for a root cause of that, for now I recommend using Microsoft Authenticator app

![duo_1](https://user-images.githubusercontent.com/77105498/165626574-6fe98a85-27a7-49eb-8f1b-afbe40626007.png)
![duo_2](https://user-images.githubusercontent.com/77105498/165626582-69c180c9-afe9-4aec-81c9-7890670ceedd.png)
<img width="268" alt="Screenshot 2022-04-27 at 22 29 43" src="https://user-images.githubusercontent.com/77105498/165626617-cd88bc36-c396-4002-b328-138398e3219d.png">

**Comment by draskomikic** [comment] 2022-04-28 08:37
Hi @jhurej sorry for not being very responsive, and thank you for looking into this issue. 

I was using version 0.3.1 with VALIDITY_PERIOD of 60 seconds.

I can confirm that Microsoft Authenticator is working with VALIDITY_PERIOD of 30 seconds.

**Closed** 2022-05-24 20:37 UTC
Labels: bug
